INSERT INTO authors (surname, name) values ('Waltari','Mika');
INSERT INTO authors (surname, name) values ('Stafford','David');
INSERT INTO authors (surname, name) values ('Kołakowski','Leszek');
INSERT INTO authors (surname, name) values ('Kaziów','Michał');
INSERT INTO authors (surname, name) values ('Levy','Marc');
INSERT INTO authors (surname, name) values ('Dobraczyński','Jan');
INSERT INTO authors (surname, name) values ('Dubois','Jacek');
INSERT INTO authors (surname, name) values ('Strękowska-Zaremba','Małgorzata');
INSERT INTO authors (surname, name) values ('Rufin','Jean-Christophe');
INSERT INTO authors (surname, name) values ('Okońska','Alicja');
INSERT INTO authors (surname, name) values ('Townsend','Sue');
INSERT INTO authors (surname, name) values ('Harr','Jonathan');
INSERT INTO authors (surname, name) values ('Schefter','Karla');
INSERT INTO authors (surname, name) values ('Gallmann','Kuki');
INSERT INTO authors (surname, name) values ('Matuszkiewicz','Irena');
INSERT INTO authors (surname, name) values ('Turowska','Zofia');
INSERT INTO authors (surname, name) values ('Brzechwa','Jan');
INSERT INTO authors (surname, name) values ('Lodge','David');
INSERT INTO authors (surname, name) values ('Józefacka','Maria Emilia');
INSERT INTO authors (surname, name) values ('Carroll','Lewis');
INSERT INTO authors (surname, name) values ('Kazan','Elia');
INSERT INTO authors (surname, name) values ('Montgomery','Lucy Maud');
INSERT INTO authors (surname, name) values ('Crais','Robert');
INSERT INTO authors (surname, name) values ('Brown','Dan');
INSERT INTO authors (surname, name) values ('Fredriksson','Marianne');
INSERT INTO authors (surname, name) values ('Szwaja','Monika');
INSERT INTO authors (surname, name) values ('Hrabal','Bohumil');
INSERT INTO authors (surname, name) values ('Kapuściński','Ryszard');
INSERT INTO authors (surname, name) values ('Akunin','Boris');
INSERT INTO authors (surname, name) values ('Auderska','Halina');
INSERT INTO authors (surname, name) values ('Perrault','Charles');
INSERT INTO authors (surname, name) values ('Papuzińska','Joanna');
INSERT INTO authors (surname, name) values ('Mickiewicz','Adam');
INSERT INTO authors (surname, name) values ('Rodziewiczówna','Maria');
INSERT INTO authors (surname, name) values ('Herbert','Zbigniew');
INSERT INTO authors (surname, name) values ('Andersen','Hans Christian');
INSERT INTO authors (surname, name) values ('Grimm','Wilhelm');
INSERT INTO authors (surname, name) values ('Matthews','Andrew');
INSERT INTO authors (surname, name) values ('Słowiński','Przemysław');
INSERT INTO authors (surname, name) values ('Andrycz','Ninia');
INSERT INTO authors (surname, name) values ('Coben','Harlan');
INSERT INTO authors (surname, name) values ('Wynne','Marcus');
INSERT INTO authors (surname, name) values ('Bruczkowski','Marcin');
INSERT INTO authors (surname, name) values ('Alexandra','Belinda');
INSERT INTO authors (surname, name) values ('Żurek','Jerzy');
INSERT INTO authors (surname, name) values ('Hofmann','Corinne');
INSERT INTO authors (surname, name) values ('Herling-Grudziński','Gustaw');
INSERT INTO authors (surname, name) values ('Gallego','Ruben');
INSERT INTO authors (surname, name) values ('Fitch','Janet');
INSERT INTO authors (surname, name) values ('Maślanka','Mariusz');
INSERT INTO authors (surname, name) values ('Pawlikowska','Beata');
INSERT INTO authors (surname, name) values ('Turow','Scott');
INSERT INTO authors (surname, name) values ('Roberts','Nora');
INSERT INTO authors (surname, name) values ('Smith','Wilbur');
INSERT INTO authors (surname, name) values ('Plain','Belva');
INSERT INTO authors (surname, name) values ('Koul','Sudha');
INSERT INTO authors (surname, name) values ('Towsend','Sue');
INSERT INTO authors (surname, name) values ('Sapkowski','Andrzej');
INSERT INTO authors (surname, name) values ('Szelburg-Zarembina','Ewa');
INSERT INTO authors (surname, name) values ('Wilbur','Smith');
INSERT INTO authors (surname, name) values ('Roy','Arundhati');
INSERT INTO authors (surname, name) values ('Kraszewski','Józef Ignacy');
INSERT INTO authors (surname, name) values ('Wojtyszko','Maciej');
INSERT INTO authors (surname, name) values ('Chmielewska','Joanna');
INSERT INTO authors (surname, name) values ('Hornby','Nick');
INSERT INTO authors (surname, name) values ('Chruślińska','Iza');
INSERT INTO authors (surname, name) values ('Budrewicz','Olgierd');
INSERT INTO authors (surname, name) values ('Huelle','Paweł');
INSERT INTO authors (surname, name) values ('Coulter','Catherine');
INSERT INTO authors (surname, name) values ('Sobolewska','Anna');
INSERT INTO authors (surname, name) values ('Shan','Sa');
INSERT INTO authors (surname, name) values ('Macdonald','Ross');
INSERT INTO authors (surname, name) values ('Świderkówna','Anna');
INSERT INTO authors (surname, name) values ('Przybył','Elżbieta');
INSERT INTO authors (surname, name) values ('Cook','Robin');
INSERT INTO authors (surname, name) values ('Connelly','Michael');
INSERT INTO authors (surname, name) values ('Sowa','Izabela');
INSERT INTO authors (surname, name) values ('Perez-Reverte','Arturo');
INSERT INTO authors (surname, name) values ('Goddard','Robert');
INSERT INTO authors (surname, name) values ('Waller','Robert James');
INSERT INTO authors (surname, name) values ('Greenhalgh','Chris');
INSERT INTO authors (surname, name) values ('Berwińska','Krystyna');
INSERT INTO authors (surname, name) values ('Bąkiewicz','Grażyna');
INSERT INTO authors (surname, name) values ('Clark','Mary Higgins');
INSERT INTO authors (surname, name) values ('Westmacott','Mary (pseud.)');
INSERT INTO authors (surname, name) values ('Dirie','Waris');
INSERT INTO authors (surname, name) values ("D'ehaem",'Jeanne');
INSERT INTO authors (surname, name) values ('Palm','Anna-Karin');
INSERT INTO authors (surname, name) values ('Parrado','Nando');
INSERT INTO authors (surname, name) values ('Duszyńska','Julia');
INSERT INTO authors (surname, name) values ('Gomulicki','Wiktor');
INSERT INTO authors (surname, name) values ('Kuncewiczowa','Maria');
INSERT INTO authors (surname, name) values ('Compton','Clare');
INSERT INTO authors (surname, name) values ('Montefiore','Santa');
INSERT INTO authors (surname, name) values ('Musierowicz','Małgorzata');
INSERT INTO authors (surname, name) values ('Ekman','Kerstin');
INSERT INTO authors (surname, name) values ('Lovett','Cameron Verney');
INSERT INTO authors (surname, name) values ('Mann','Tomasz');
INSERT INTO authors (surname, name) values ('Domino','Zbigniew');
INSERT INTO authors (surname, name) values ('Madison','Susan');
INSERT INTO authors (surname, name) values ('Harris','Joanne');
INSERT INTO authors (surname, name) values ('Binchy','Maeve');
INSERT INTO authors (surname, name) values ('Clancy','Tom');
INSERT INTO authors (surname, name) values ('Rylski','Eustachy');
INSERT INTO authors (surname, name) values ('Renard','Maurycy');
INSERT INTO authors (surname, name) values ('Grisham','John');
INSERT INTO authors (surname, name) values ('Archer','Jeffrey');
INSERT INTO authors (surname, name) values ('Dumas','Aleksander');
INSERT INTO authors (surname, name) values ('Chevalier','Tracy');
INSERT INTO authors (surname, name) values ('Lowry','Lois');
INSERT INTO authors (surname, name) values ('Delbanco','Nicholas');
INSERT INTO authors (surname, name) values ('Bidwell','George');
INSERT INTO authors (surname, name) values ('Kellerman','Jonathan');
INSERT INTO authors (surname, name) values ('Fielding','Joy');
INSERT INTO authors (surname, name) values ('Samson','Andrzej');
INSERT INTO authors (surname, name) values ('Eichelberger','Wojciech');
INSERT INTO authors (surname, name) values ('Flagg','Fannie');
INSERT INTO authors (surname, name) values ('Mularczyk','Andrzej');
INSERT INTO authors (surname, name) values ('Janicki','Jerzy');
INSERT INTO authors (surname, name) values ('Davidar','David');
INSERT INTO authors (surname, name) values ('James','Henry');
INSERT INTO authors (surname, name) values ('Wharton','William');
INSERT INTO authors (surname, name) values ('Kalicińska','Małgorzata');
INSERT INTO authors (surname, name) values ('Steel','Danielle');
INSERT INTO authors (surname, name) values ('Link','Charlotte');
INSERT INTO authors (surname, name) values ('Dubus','III Andre');
INSERT INTO authors (surname, name) values ('Ridpath','Michael');
INSERT INTO authors (surname, name) values ('Baranowski','Krzysztof');
INSERT INTO authors (surname, name) values ('Goudge','Eileen');
INSERT INTO authors (surname, name) values ('Holland','Tom');
INSERT INTO authors (surname, name) values ('Dailey','Janet');
INSERT INTO authors (surname, name) values ('Karolak','Hanna');
INSERT INTO authors (surname, name) values ('Verne','Juliusz');
INSERT INTO authors (surname, name) values ('Canty','Kevin');
INSERT INTO authors (surname, name) values ('Spencer','LaVyrle');
INSERT INTO authors (surname, name) values ('Nurowska','Maria');
INSERT INTO authors (surname, name) values ('Murdoch','Iris');
INSERT INTO authors (surname, name) values ('Prus','Bolesław');
INSERT INTO authors (surname, name) values ('Rogoszówna','Zofia');
INSERT INTO authors (surname, name) values ('Lindgren','Astrid');
INSERT INTO authors (surname, name) values ('Sasson','Jean');
INSERT INTO authors (surname, name) values ('Rivers','Francine');
INSERT INTO authors (surname, name) values ('Levin','Ira');
INSERT INTO authors (surname, name) values ('Żeromski','Stefan');
INSERT INTO authors (surname, name) values ('Lewicki','Zbigniew');
INSERT INTO authors (surname, name) values ('Fielding','Helen');
INSERT INTO authors (surname, name) values ('Gertler','Stephanie');
INSERT INTO authors (surname, name) values ('Wilson','Jacqueline');
INSERT INTO authors (surname, name) values ('Plebanek','Grażyna');
INSERT INTO authors (surname, name) values ('DiCamillo','Kate');
INSERT INTO authors (surname, name) values ('Piekarska','Małgorzata Karolina');
INSERT INTO authors (surname, name) values ('Martin','Steve');
INSERT INTO authors (surname, name) values ('Davies','Norman');
INSERT INTO authors (surname, name) values ('Mańczyk','Agata');
INSERT INTO authors (surname, name) values ('Koontz','Dean');
INSERT INTO authors (surname, name) values ('Lagatree','Kirsten M.');
INSERT INTO authors (surname, name) values ('Timmermans','Feliks');
INSERT INTO authors (surname, name) values ('Cieński','Marcin');
INSERT INTO authors (surname, name) values ('Herrera','Hayden');
INSERT INTO authors (surname, name) values ('Osiecka','Agnieszka');
INSERT INTO authors (surname, name) values ('Hemar','Marian');
INSERT INTO authors (surname, name) values ('Carroll','Jonathan');
INSERT INTO authors (surname, name) values ('Baldwin','James');
INSERT INTO authors (surname, name) values ('Puzo','Mario');
INSERT INTO authors (surname, name) values ('Cornwell','Patricia');
INSERT INTO authors (surname, name) values ('Kuczok','Wojciech');
INSERT INTO authors (surname, name) values ('Stark','Richard');
INSERT INTO authors (surname, name) values ('Cunningham','Michael');
INSERT INTO authors (surname, name) values ('Jastrun','Tomasz');
INSERT INTO authors (surname, name) values ('Kowalewska','Hanna');
INSERT INTO authors (surname, name) values ('Norman','Hilary');
INSERT INTO authors (surname, name) values ('Pastuszek','Andrzej');
INSERT INTO authors (surname, name) values ('Cejrowski','Wojciech');
INSERT INTO authors (surname, name) values ('Królikowski','Bohdan');
INSERT INTO authors (surname, name) values ('Woolrich','Cornell');
INSERT INTO authors (surname, name) values ('Spinelli','Jerry');
INSERT INTO authors (surname, name) values ('Harris','Thomas');
INSERT INTO authors (surname, name) values ('Coetzee','J. M.');
INSERT INTO authors (surname, name) values ('Rowling','Joanne K.');
INSERT INTO authors (surname, name) values ('Tyldesley','Joyce');
INSERT INTO authors (surname, name) values ('Bellow','Saul');
INSERT INTO authors (surname, name) values ('Onichimowska','Anna');
INSERT INTO authors (surname, name) values ('Szczurek','Józef');
INSERT INTO authors (surname, name) values ('Grodecka','Ewa');
INSERT INTO authors (surname, name) values ('LeSueur','Alec');
INSERT INTO authors (surname, name) values ('Zborowska','z Kobuszewskich Hanna');
INSERT INTO authors (surname, name) values ('Nielsen','Jeri');
INSERT INTO authors (surname, name) values ('Bakuła','Hanna');
INSERT INTO authors (surname, name) values ('Tamaro','Susanna');
INSERT INTO authors (surname, name) values ('Eco','Umberto');
INSERT INTO authors (surname, name) values ('Iggulden','Conn');
INSERT INTO authors (surname, name) values ('Goleman','Daniel');
INSERT INTO authors (surname, name) values ('Dziewoński','Roman');
INSERT INTO authors (surname, name) values ('Bayley','John');
INSERT INTO authors (surname, name) values ('Duczmal','Małgorzata');
INSERT INTO authors (surname, name) values ('Carpenter','Humphrey');
INSERT INTO authors (surname, name) values ('Janosch','Janosch');
INSERT INTO authors (surname, name) values ('Tryzwan','Mariola');
INSERT INTO authors (surname, name) values ('Grochola','Katarzyna');
INSERT INTO authors (surname, name) values ('Jaworczakowa','Mira');
INSERT INTO authors (surname, name) values ('Stasiuk','Andrzej');
INSERT INTO authors (surname, name) values ('Allbeury','Ted');
INSERT INTO authors (surname, name) values ('Legut','Lucyna');
INSERT INTO authors (surname, name) values ('Tochman','Wojciech');
INSERT INTO authors (surname, name) values ('Twain','Mark');
INSERT INTO authors (surname, name) values ('Somoza','Jose Carlos');
INSERT INTO authors (surname, name) values ('Allison','Dorothy');
INSERT INTO authors (surname, name) values ('Khadra','Yasmina');
INSERT INTO authors (surname, name) values ('Coelho','Paulo');
INSERT INTO authors (surname, name) values ('Baricco','Alessandro');
INSERT INTO authors (surname, name) values ('Hannah','Kristin');
INSERT INTO authors (surname, name) values ('Bond','Michael');
INSERT INTO authors (surname, name) values ('Brandstaetter','Roman');
INSERT INTO authors (surname, name) values ('Nałęcz','Daria');
INSERT INTO authors (surname, name) values ('Crichton','Michael');
INSERT INTO authors (surname, name) values ('Niziurski','Edmund');
INSERT INTO authors (surname, name) values ('Grodzieńska','Stefania');
INSERT INTO authors (surname, name) values ('Kertesz','Imre');
INSERT INTO authors (surname, name) values ('Albiński','Wojciech');
INSERT INTO authors (surname, name) values ('Van','Campenhout Herman');
INSERT INTO authors (surname, name) values ('Siesicka','Krystyna');
INSERT INTO authors (surname, name) values ('Mielke','Thomas R. P.');
INSERT INTO authors (surname, name) values ('Raczek','Tomasz');
INSERT INTO authors (surname, name) values ('Mawer','Simon');
INSERT INTO authors (surname, name) values ('Szczeklik','Andrzej');
INSERT INTO authors (surname, name) values ('Paul','Allen');
INSERT INTO authors (surname, name) values ('Essex','Karen');
INSERT INTO authors (surname, name) values ('Andrasiewicz','Jarosław');
INSERT INTO authors (surname, name) values ('Stomma','Ludwik');
INSERT INTO authors (surname, name) values ('Dominik','Tomasz');
INSERT INTO authors (surname, name) values ('Gavalda','Anna');
INSERT INTO authors (surname, name) values ('Lynds','Gayle');
INSERT INTO authors (surname, name) values ('Ludlum','Robert');
INSERT INTO authors (surname, name) values ('Pałyga','Artur');
INSERT INTO authors (surname, name) values ('Webster','David Kenyon');
INSERT INTO authors (surname, name) values ('Hemingway','Ernest');
INSERT INTO authors (surname, name) values ('Masterton','Graham');
INSERT INTO authors (surname, name) values ('Russo','Richard');
INSERT INTO authors (surname, name) values ('Berling','Peter');
INSERT INTO authors (surname, name) values ('Evans','Max');
INSERT INTO authors (surname, name) values ('Durrell','Gerald Malcolm');
INSERT INTO authors (surname, name) values ('Nothomb','Amelie');
INSERT INTO authors (surname, name) values ('Wilson','Ian');
INSERT INTO authors (surname, name) values ('Lancelyn','Green Roger');
INSERT INTO authors (surname, name) values ('Holt','Victoria');
INSERT INTO authors (surname, name) values ('Funke','Cornelia');
INSERT INTO authors (surname, name) values ('Scholes','Katherine');
INSERT INTO authors (surname, name) values ('Fatchen','Max');
INSERT INTO authors (surname, name) values ('Klawe','Jacek');
INSERT INTO authors (surname, name) values ('Tafil-Klawe','Małgorzata');
INSERT INTO authors (surname, name) values ('Martin','Beverly S.');
INSERT INTO authors (surname, name) values ('Śliwa','Zuzanna');
INSERT INTO authors (surname, name) values ('Sienkiewicz','Henryk');
INSERT INTO authors (surname, name) values ('Patterson','James');
INSERT INTO authors (surname, name) values ('Gross','Andrew');
INSERT INTO authors (surname, name) values ('Tischner','Józef ks.');
INSERT INTO authors (surname, name) values ('Greer','Luanshya');
INSERT INTO authors (surname, name) values ('Andrews','Virginia C.');
INSERT INTO authors (surname, name) values ('Woolfolk','Cross Donna');
INSERT INTO authors (surname, name) values ('Balzac','Honoriusz');
INSERT INTO authors (surname, name) values ('Siddons','Anne Rivers');
INSERT INTO authors (surname, name) values ('Poniewierski','Janusz');
INSERT INTO authors (surname, name) values ('Axelsson','Majgull');
INSERT INTO authors (surname, name) values ('Kuropatnicka-Salamon','Halina');
INSERT INTO authors (surname, name) values ('Jansson','Tove');
INSERT INTO authors (surname, name) values ('Oberto','Varinia');
INSERT INTO authors (surname, name) values ('Le','Guin Ursula');
INSERT INTO authors (surname, name) values ('Gordon','Noah');
INSERT INTO authors (surname, name) values ('Kofta','Krystyna');
INSERT INTO authors (surname, name) values ('Sparks','Nicholas');
INSERT INTO authors (surname, name) values ('Machowiak','Stanisław L.');
INSERT INTO authors (surname, name) values ('Wiśniewski','Janusz L.');
INSERT INTO authors (surname, name) values ('Follett','Ken');
INSERT INTO authors (surname, name) values ('Higgins','Jack');
INSERT INTO authors (surname, name) values ('Faunce','John');
INSERT INTO authors (surname, name) values ('Kovacs','Istvan');
INSERT INTO authors (surname, name) values ('Abramow-Newerly','Jarosław');
INSERT INTO authors (surname, name) values ('Twardowski','Jan ks.');
INSERT INTO authors (surname, name) values ('Sadaj','Ryszard');
INSERT INTO authors (surname, name) values ('Al-Salami','Khadija');
INSERT INTO authors (surname, name) values ('Hay','Elizabeth');
INSERT INTO authors (surname, name) values ('Gaarder','Jostein');
INSERT INTO authors (surname, name) values ('Fast','Howard');
INSERT INTO authors (surname, name) values ('Ishiguro','Kazuo');
INSERT INTO authors (surname, name) values ('Burnett','Frances');
INSERT INTO authors (surname, name) values ('Elisabeth','Hodgson');
INSERT INTO authors (surname, name) values ('La','Borie Guillemette de');
INSERT INTO authors (surname, name) values ('Stępkowska-Szwed','Maria');
INSERT INTO authors (surname, name) values ('Pattison','Eliot');
INSERT INTO authors (surname, name) values ('Buchanan','Edna');
INSERT INTO authors (surname, name) values ('Frankl','Roman');
INSERT INTO authors (surname, name) values ('Lindo','Elvira');
INSERT INTO authors (surname, name) values ('Moravia','Alberto');
INSERT INTO authors (surname, name) values ('Brandys','Kazimierz');
INSERT INTO authors (surname, name) values ('Różewicz','Tadeusz');
INSERT INTO authors (surname, name) values ('Parsons','Tony');
INSERT INTO authors (surname, name) values ('Gray','John');
INSERT INTO authors (surname, name) values ('Pilch','Jerzy');
INSERT INTO authors (surname, name) values ('London','Jack');
INSERT INTO authors (surname, name) values ('Pruszyńska','Anna');
INSERT INTO authors (surname, name) values ('Pruszyński','Mieczysław');
INSERT INTO authors (surname, name) values ('Odojewski','Włodzimierz');
INSERT INTO authors (surname, name) values ('Hermann','Kai');
INSERT INTO authors (surname, name) values ('Waldemar','Charles');
INSERT INTO authors (surname, name) values ('King','Stephen');
INSERT INTO authors (surname, name) values ('Docx','Edward');
INSERT INTO authors (surname, name) values ('Kim','Elizabeth');
INSERT INTO authors (surname, name) values ('Jagielski','Wojciech');
INSERT INTO authors (surname, name) values ('Bojarska','Anna');
INSERT INTO authors (surname, name) values ('Morgan','Richard');
INSERT INTO authors (surname, name) values ('Mańkowska','Klementyna');
INSERT INTO authors (surname, name) values ('Himilsbach','Jan');
INSERT INTO authors (surname, name) values ('Mankell','Henning');
INSERT INTO authors (surname, name) values ('Wawryniuk','Beata');
INSERT INTO authors (surname, name) values ('Hen','Józef');
INSERT INTO authors (surname, name) values ('OFaolain','Nuala');
INSERT INTO authors (surname, name) values ('Forsyth','Frederick');
INSERT INTO authors (surname, name) values ('Makine','Andrei');
INSERT INTO authors (surname, name) values ('Gelb','Michael J.');
INSERT INTO authors (surname, name) values ('Christie','Agata');
INSERT INTO authors (surname, name) values ('Na','bajkowy sen');
INSERT INTO authors (surname, name) values ('Messner','Reinhold');
INSERT INTO authors (surname, name) values ('Sedlak','Włodzimierz ks.');
INSERT INTO authors (surname, name) values ('Loth','Roman');
INSERT INTO authors (surname, name) values ('Suchocki','Jerzy R.');
INSERT INTO authors (surname, name) values ('Wiśniewski','Grzegorz');
INSERT INTO authors (surname, name) values ('Shakib','Siba');
INSERT INTO authors (surname, name) values ('Eliza','Orzeszkowa');
INSERT INTO authors (surname, name) values ('Roszkowski','Wojciech');
INSERT INTO authors (surname, name) values ('Grupińska','Anka');
INSERT INTO authors (surname, name) values ('Hugo','Wiktor');
INSERT INTO authors (surname, name) values ('Tyszkiewicz','Beata');
INSERT INTO authors (surname, name) values ('Grzegorczyk','Jan');
INSERT INTO authors (surname, name) values ('Zweig','Stefan');
INSERT INTO authors (surname, name) values ('Goldsmith','Olivia');
INSERT INTO authors (surname, name) values ('Christie','Agatha');
INSERT INTO authors (surname, name) values ('McEwan','Ian');
INSERT INTO authors (surname, name) values ('Singer','Isaac Bashevis');
INSERT INTO authors (surname, name) values ('Bukowska','Paulina');
INSERT INTO authors (surname, name) values ('Kundera','Milan');
INSERT INTO authors (surname, name) values ('Zweig','Stefanie');
INSERT INTO authors (surname, name) values ('Tomaszewska','Marta');
INSERT INTO authors (surname, name) values ('Dąbrowska','Maria');
INSERT INTO authors (surname, name) values ('Sebold','Alice');
INSERT INTO authors (surname, name) values ('Konopnicka','Maria');
INSERT INTO authors (surname, name) values ('Pisarski','Roman');
INSERT INTO authors (surname, name) values ('Gałczyńska','Natalia');
INSERT INTO authors (surname, name) values ('Siedlecka','Joanna');
INSERT INTO authors (surname, name) values ('Raspail','Jean');
INSERT INTO authors (surname, name) values ('Ondaatje','Michael');
INSERT INTO authors (surname, name) values ('Mourad','Kenize');
INSERT INTO authors (surname, name) values ('Pilcher','Rosamunde');
INSERT INTO authors (surname, name) values ('Kolonko','Mariusz Max');
INSERT INTO authors (surname, name) values ('Kurson','Robert');
INSERT INTO authors (surname, name) values ('Shaw','Patricia');
INSERT INTO authors (surname, name) values ('Stewart','Mary');
INSERT INTO authors (surname, name) values ('Pressfield','Steven');
INSERT INTO authors (surname, name) values ('Smith','Deborah');
INSERT INTO authors (surname, name) values ('Burchacka','Irena');
INSERT INTO authors (surname, name) values ('Lem','Stanisław');
INSERT INTO authors (surname, name) values ('Fisher','John');
INSERT INTO authors (surname, name) values ('Buchheim','Lothar-Guinther');
INSERT INTO authors (surname, name) values ('Marryat','Frederick');
INSERT INTO authors (surname, name) values ('Lelonkiewicz','Jacek');
INSERT INTO authors (surname, name) values ('Mendoza','Eduardo');
INSERT INTO authors (surname, name) values ('Lyndos','Gayle');
INSERT INTO authors (surname, name) values ('Żuchowski','Henryk Ryszard');
INSERT INTO authors (surname, name) values ('Piskorski','Krzysztof');
INSERT INTO authors (surname, name) values ('Beauman','Sally');
INSERT INTO authors (surname, name) values ('Schmitt','Eric-Emmanuel');
INSERT INTO authors (surname, name) values ('Johansen','Iris');
INSERT INTO authors (surname, name) values ('Zimler','Richard');
INSERT INTO authors (surname, name) values ('Manfredi','Valerio Massimo');
INSERT INTO authors (surname, name) values ('Cunxin','Li');
INSERT INTO authors (surname, name) values ('Picciotto','Richard');
INSERT INTO authors (surname, name) values ('Paisner','Daniel');
INSERT INTO authors (surname, name) values ('Cholewa-Selo','Anna');
INSERT INTO authors (surname, name) values ('Grafton','Sue');
INSERT INTO authors (surname, name) values ('Palmer','Michael');
INSERT INTO authors (surname, name) values ('Konwicki','Tadeusz');
INSERT INTO authors (surname, name) values ('Lepecki','Mieczysław');
INSERT INTO authors (surname, name) values ('Łuszczewska','Jadwiga');
INSERT INTO authors (surname, name) values ('Cabot','Meg');
INSERT INTO authors (surname, name) values ('Arct','Bohdan');
INSERT INTO authors (surname, name) values ('Makela','Hanu');
INSERT INTO authors (surname, name) values ('Woolf','Virginia');
INSERT INTO authors (surname, name) values ('Woodwar','Bill');
INSERT INTO authors (surname, name) values ('Albright','Madeleine');
INSERT INTO authors (surname, name) values ('Mniszek','Helena');
INSERT INTO authors (surname, name) values ('Oz','Amos');
INSERT INTO authors (surname, name) values ('Vreeland','Susan');
INSERT INTO authors (surname, name) values ('Pałkiewicz','Jacek');
INSERT INTO authors (surname, name) values ('Seymour-Tułasiewicz','Lilian');
INSERT INTO authors (surname, name) values ('Barlow','James');
INSERT INTO authors (surname, name) values ('Nahai','Gina Barkhordar');
INSERT INTO authors (surname, name) values ('Domańska','Antonina');
INSERT INTO authors (surname, name) values ('Marianowicz','Antoni');
INSERT INTO authors (surname, name) values ('Zającówna','Janina');
INSERT INTO authors (surname, name) values ('Krawczuk','Aleksander');
INSERT INTO authors (surname, name) values ('Sagan','Francoise');
INSERT INTO authors (surname, name) values ('Garnett','Cliff');
INSERT INTO authors (surname, name) values ('Jakes','John');
INSERT INTO authors (surname, name) values ('Molist','Jorge');
INSERT INTO authors (surname, name) values ('Ścibor-Rylski','Aleksander');
INSERT INTO authors (surname, name) values ('Rosenberg','Nancy Taylor');
INSERT INTO authors (surname, name) values ('Delerm','Philippe');
INSERT INTO authors (surname, name) values ('Doyle','Arthur Conan');
INSERT INTO authors (surname, name) values ('Miłosz','Czesław');
INSERT INTO authors (surname, name) values ('Pieśń','o Rolandzie (poemat)');
INSERT INTO authors (surname, name) values ('McCullough','Colleen');
INSERT INTO authors (surname, name) values ('Zubrzycki','Witold');
INSERT INTO authors (surname, name) values ('Domagalik','Janusz');
INSERT INTO authors (surname, name) values ('Gąsiorowski','Wacław');
INSERT INTO authors (surname, name) values ('Dored','Elisabeth');
INSERT INTO authors (surname, name) values ('Barrie','James Matthew');
INSERT INTO authors (surname, name) values ('Szczygielski','Marcin');
INSERT INTO authors (surname, name) values ('Kownacka','Maria');
INSERT INTO authors (surname, name) values ('Hearn','Lian');
INSERT INTO authors (surname, name) values ('Terakowska','Dorota');
INSERT INTO authors (surname, name) values ('Grodzicki','Janusz');
INSERT INTO authors (surname, name) values ('Strumiłło-Miłosz','Grażyna');
INSERT INTO authors (surname, name) values ('Kraft','Ruth');
INSERT INTO authors (surname, name) values ('Hyde','Catherine Ryan');
INSERT INTO authors (surname, name) values ('Berger','Thomas');
INSERT INTO authors (surname, name) values ('Ławecki','Tomasz');
INSERT INTO authors (surname, name) values ('Stettner-Stefańska','Barbara');
INSERT INTO authors (surname, name) values ('Olchowik-Adamowska','Liliana');
INSERT INTO authors (surname, name) values ('Morrell','David');
INSERT INTO authors (surname, name) values ('Gałczyński','Konstanty Ildefons');
INSERT INTO authors (surname, name) values ('Niemirski','Arkadiusz');
INSERT INTO authors (surname, name) values ('Cobbold','Marika');
INSERT INTO authors (surname, name) values ('Koneczny','Feliks');
INSERT INTO authors (surname, name) values ('Harris','Robert');
INSERT INTO authors (surname, name) values ('McCourt','Frank');
INSERT INTO authors (surname, name) values ('Schaeffer','Frank');
INSERT INTO authors (surname, name) values ('Allende','Isabel');
INSERT INTO authors (surname, name) values ('Quindlen','Anna');
INSERT INTO authors (surname, name) values ('Barry','Desmond');
INSERT INTO authors (surname, name) values ('Cowell','Stephanie');
INSERT INTO authors (surname, name) values ('Salij','OP Jacek');
INSERT INTO authors (surname, name) values ('Bourdin','Francoise');
INSERT INTO authors (surname, name) values ('Potter','Beatrix');
INSERT INTO authors (surname, name) values ('Brandt','Ann');
INSERT INTO authors (surname, name) values ('Rosalind','Miles');
INSERT INTO authors (surname, name) values ('Dziwisz','Stanisław Kard.');
INSERT INTO authors (surname, name) values ('Drążek','SJ Czesław o.');
INSERT INTO authors (surname, name) values ('Fleszarowa-Muskat','Stanisława');
INSERT INTO authors (surname, name) values ('Manchester','William');
INSERT INTO authors (surname, name) values ('Gardner','Katy');
INSERT INTO authors (surname, name) values ('Keitlen','Tomi');
INSERT INTO authors (surname, name) values ('Lobsenz','Norman M.');
INSERT INTO authors (surname, name) values ('Sikorski','Jerzy');
INSERT INTO authors (surname, name) values ('Robards','Karen');
INSERT INTO authors (surname, name) values ('Szczepański','Jan Józef');
INSERT INTO authors (surname, name) values ('Groom','Winston');
INSERT INTO authors (surname, name) values ('Nair','Anita');
INSERT INTO authors (surname, name) values ('Du','Maurier Daphne');
INSERT INTO authors (surname, name) values ('Evans','Nicholas');
INSERT INTO authors (surname, name) values ('May','Karol');
INSERT INTO authors (surname, name) values ('Frassati-Gawrońska','Luciana');
INSERT INTO authors (surname, name) values ('Bockenheim','Krystyna');
INSERT INTO authors (surname, name) values ('Clark','Carol Higgins');
INSERT INTO authors (surname, name) values ('Perez-Reverte','Arturo i Carlota');
INSERT INTO authors (surname, name) values ('Nosow','Mikołaj');
INSERT INTO authors (surname, name) values ('Parandowski','Jan');
INSERT INTO authors (surname, name) values ('Clark','Brenda');
INSERT INTO authors (surname, name) values ('LeCarre','John');
INSERT INTO authors (surname, name) values ('Kossak-Szczucka','Zofia');
INSERT INTO authors (surname, name) values ('Remarque','Erich Maria');
INSERT INTO authors (surname, name) values ('Horwath','Witold');
INSERT INTO authors (surname, name) values ('Hayder','Mo');
INSERT INTO authors (surname, name) values ('Gołubiew','Antoni');
INSERT INTO authors (surname, name) values ('Liosa','Mario Vargas');
INSERT INTO authors (surname, name) values ('Gojawiczyńska','Pola');
INSERT INTO authors (surname, name) values ('Saylor','Steven');
INSERT INTO authors (surname, name) values ('Osiatyński','Wiktor');
INSERT INTO authors (surname, name) values ('Wilson','Steven');
INSERT INTO authors (surname, name) values ('Antczak','Jacek');
INSERT INTO authors (surname, name) values ('Simenon','Georges');
INSERT INTO authors (surname, name) values ('Zaorski','Andrzej');
INSERT INTO authors (surname, name) values ('Brackett','Leigh');
INSERT INTO authors (surname, name) values ("L'Engle",'Madeleine');
INSERT INTO authors (surname, name) values ('Michalak','Stefan');
INSERT INTO authors (surname, name) values ('Camus','David');
INSERT INTO authors (surname, name) values ('Lehane','Dennis');
INSERT INTO authors (surname, name) values ('Galsworthy','John');
INSERT INTO authors (surname, name) values ('Wiśniewski','Janusz Leon');
INSERT INTO authors (surname, name) values ('Silva','Jose');
INSERT INTO authors (surname, name) values ('Stone','Robert B.');
INSERT INTO authors (surname, name) values ('Durschmied','Erik');
INSERT INTO authors (surname, name) values ('Vandenberg','Philipp');
INSERT INTO authors (surname, name) values ('Mayes','Frances');
INSERT INTO authors (surname, name) values ('Weyssenhoff','Józef');
INSERT INTO authors (surname, name) values ('Parkinson','Cyril Northcote');
INSERT INTO authors (surname, name) values ('Carr','Philippa');
INSERT INTO authors (surname, name) values ('Heyerdahl','Thor');
INSERT INTO authors (surname, name) values ('Wolfe','Thomas');
INSERT INTO authors (surname, name) values ('Mahmoody','Betty');
INSERT INTO authors (surname, name) values ('Reilly','Matthew');
INSERT INTO authors (surname, name) values ('Spencer','Scott');
INSERT INTO authors (surname, name) values ('Mason','Daniel');
INSERT INTO authors (surname, name) values ('Pantaeva','Irina');
INSERT INTO authors (surname, name) values ('Buck','Pearl S.');
INSERT INTO authors (surname, name) values ('Conrad','Joseph');
INSERT INTO authors (surname, name) values ('Curwood','James Oliver');
INSERT INTO authors (surname, name) values ('Porazińska','Janina');
INSERT INTO authors (surname, name) values ('Załuski','Marian');
INSERT INTO authors (surname, name) values ('McClure','Ken');
INSERT INTO authors (surname, name) values ('Atwood','Margaret');
INSERT INTO authors (surname, name) values ('Krajewski','Marek');
INSERT INTO authors (surname, name) values ('Gimenez-Bartlett','Alicia');
INSERT INTO authors (surname, name) values ('Ostrowicka','Beata');
INSERT INTO authors (surname, name) values ('Wilson','Susan');
INSERT INTO authors (surname, name) values ('Ożogowska','Hanna');
INSERT INTO authors (surname, name) values ('Mostwin','Danuta');
INSERT INTO authors (surname, name) values ('Orłoś','Maciej');
INSERT INTO authors (surname, name) values ('Wołoszański','Bogusław');
INSERT INTO authors (surname, name) values ('Karski','Jan');
INSERT INTO authors (surname, name) values ('Krall','Hanna');
INSERT INTO authors (surname, name) values ('Kalicka','Manuela');
INSERT INTO authors (surname, name) values ('Andrzejczuk','Beata');
INSERT INTO authors (surname, name) values ('Rejmer','Małgorzata');
INSERT INTO authors (surname, name) values ('Szklarski','Alfred');
INSERT INTO authors (surname, name) values ('Alarcón','Pedro Antonio');
INSERT INTO authors (surname, name) values ('Jerome','K. Jerome');
INSERT INTO authors (surname, name) values ('Moggach','Deborah');
INSERT INTO authors (surname, name) values ('Mailer','Norman');
INSERT INTO authors (surname, name) values ('Selimović','Mesa');
INSERT INTO authors (surname, name) values ('Parsons','Julie');
INSERT INTO authors (surname, name) values ('Alcott','Louisa May');
INSERT INTO authors (surname, name) values ('Kruger','Maria');
INSERT INTO authors (surname, name) values ('Gilstrap','John');
INSERT INTO authors (surname, name) values ('Śliwowska','Wiktoria');
INSERT INTO authors (surname, name) values ('Latifa','L');
INSERT INTO authors (surname, name) values ('Coonts','Stephen');
INSERT INTO authors (surname, name) values ('Kosmowska','Barbara');
INSERT INTO authors (surname, name) values ('Pritchett','Victor Sawdon');
INSERT INTO authors (surname, name) values ('Riley','Judith Mertle');
INSERT INTO authors (surname, name) values ('O.Hanlon','Redmond');
INSERT INTO authors (surname, name) values ('Ostroch','Aleksandra');
INSERT INTO authors (surname, name) values ('Howatch','Susan');
INSERT INTO authors (surname, name) values ('Sisman','Robyn');
INSERT INTO authors (surname, name) values ('Wouk','Herman');
INSERT INTO authors (surname, name) values ('Landvik','Lorna');
INSERT INTO authors (surname, name) values ('Ellroy','James');
INSERT INTO authors (surname, name) values ('Tuwim','Julian');
INSERT INTO authors (surname, name) values ('Flagg','Fennie');
INSERT INTO authors (surname, name) values ('Flynn','Vince');
INSERT INTO authors (surname, name) values ('Nowak','Tadeusz');
INSERT INTO authors (surname, name) values ('Sołżenicyn','Aleksander');
INSERT INTO authors (surname, name) values ('Greeley','Andrew M.');
INSERT INTO authors (surname, name) values ('Douglas','Lloyd C.');
INSERT INTO authors (surname, name) values ('Dahl','Roald');
INSERT INTO authors (surname, name) values ('Papuzińska','Magda');
INSERT INTO authors (surname, name) values ('Mayle','Peter');
INSERT INTO authors (surname, name) values ('Krakauer','Jon');
INSERT INTO authors (surname, name) values ('Urbańczyk','Andrzej');
INSERT INTO authors (surname, name) values ('Hartwig','Julia');
INSERT INTO authors (surname, name) values ('Irving','John');
INSERT INTO authors (surname, name) values ('Stevenson','Robert Louis');
INSERT INTO authors (surname, name) values ('Rice','Anne');
INSERT INTO authors (surname, name) values ('Szczypiorski','Andrzej');
INSERT INTO authors (surname, name) values ('Zapolska','Gabriela');
INSERT INTO authors (surname, name) values ('Brzezińska','Anna');
INSERT INTO authors (surname, name) values ('Szczepańska','Agnieszka');
INSERT INTO authors (surname, name) values ('Michałkow','Sergiusz');
INSERT INTO authors (surname, name) values ('Smith','Sarah');
INSERT INTO authors (surname, name) values ('Shaw','Irwin');
INSERT INTO authors (surname, name) values ('Wyszyński','Stefan Kardynał');
INSERT INTO authors (surname, name) values ('Parker','Barbara');
INSERT INTO authors (surname, name) values ('Dostojewski','Fiodor');
INSERT INTO authors (surname, name) values ('Majcherczyk','Jerzy');
INSERT INTO authors (surname, name) values ('Reymont','Władysław Stanisław');
INSERT INTO authors (surname, name) values ('Frazier','Charles');
INSERT INTO authors (surname, name) values ('Moore','Brian');
INSERT INTO authors (surname, name) values ('Ehle','John');
INSERT INTO authors (surname, name) values ('Książkiewicz','Teodor o.');
INSERT INTO authors (surname, name) values ('Stone','Katherine');
INSERT INTO authors (surname, name) values ('Jokai','Mor');
INSERT INTO authors (surname, name) values ('Tyrmand','Leopold');
INSERT INTO authors (surname, name) values ('Zielińska-Zamora','Iwona');
INSERT INTO authors (surname, name) values ('Arias','Juan');
INSERT INTO authors (surname, name) values ('Kelly','Neil');
INSERT INTO authors (surname, name) values ('Salzman','Mark');
INSERT INTO authors (surname, name) values ('Wolitzer','Meg');
